# Generated by Django 3.0.4 on 2020-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200322_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'disabled'), (1, 'active')], default=1),
        ),
    ]
