# Generated by Django 3.0.4 on 2020-03-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200324_2152'),
    ]

    operations = [
        migrations.RenameField('event', 'organizer_decription', 'organizer_description'),
    ]
