# Generated by Django 3.0.5 on 2020-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200328_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='blank101.png', upload_to='assets/img'),
        ),
    ]
