# Generated by Django 3.0.5 on 2020-05-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200503_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='blank100.png', upload_to='assets/img'),
        ),
    ]
