# Generated by Django 3.0.5 on 2020-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200503_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='blank101.png', upload_to='event_image'),
        ),
    ]
